// Code generated by Wire. DO NOT EDIT.

//go:generate wire
//+build !wireinject

package migrate

import (
	"github.com/marcusyip/golang-wire-mongo/config"
	"github.com/marcusyip/golang-wire-mongo/core/logger"
	"github.com/marcusyip/golang-wire-mongo/db/migrates"
	"github.com/marcusyip/golang-wire-mongo/repositories"
)

// Injectors from wire.go:

func NewMigrationJob() (*migrates.MigrationJob, error) {
	logrusLogger := logger.New()
	configConfig := config.ProvideConfig()
	client, err := repositories.NewClient(configConfig)
	if err != nil {
		return nil, err
	}
	database := repositories.NewDatabase(configConfig, client)
	migrationJob := migrates.NewMigrationJob(logrusLogger, database)
	return migrationJob, nil
}
